[package]
name = "lmfit_derive"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
description = "Derive macro for lmfit curve models"
license = "MIT"
readme = "README.md"
repository = "https://github.com/XNCZ/lmfit"
keywords = ["curve-fitting", "deriving", "macros", "optimization"]
categories = ["development-tools"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
