//! The seam between a model, the derive macro, and the solver.
//!
//! Four traits live here, and they split the work cleanly:
//!
//! * [`ModelParams`] is *layout* — which fields exist, in what order, and how
//!   to read and write them. It is generated by `#[derive(Model)]`; users
//!   never write it by hand.
//! * [`Curve`] is *arithmetic* — what the model computes. Users write one
//!   required method, and it reads like the formula it implements; an
//!   optional second method hands the solver analytic partial derivatives.
//! * [`ComplexCurve`] is the complex-valued sibling of [`Curve`]: complex in,
//!   complex out, real parameters.
//! * [`PartialValues`] is the *optional* analytic-partials accessor: what a
//!   model returns from `partials_at` instead of leaving the derivatives to
//!   finite differences.
//!
//! Neither the derive macro nor the solver knows about the other. The derive
//! only ever produces an impl of `ModelParams`; the solver only ever consumes
//! one. That is what lets the two evolve independently — a change to how
//! parameters are stored never touches the solver, and a change of solver
//! never touches the macro.

use crate::error::Result;
use crate::parameter::{Parameter, Parameters};
use crate::result::{ComplexResult, ModelResult};
use num_complex::Complex64;

/// Metadata describing one fittable field of a model.
///
/// Generated per field by `#[derive(Model)]`.
#[derive(Debug, Clone, PartialEq)]
pub struct ParamSpec {
    /// The field's name.
    pub name: String,
    /// Value the fit starts from.
    pub value: f64,
    /// Lower bound, if any.
    pub min: Option<f64>,
    /// Upper bound, if any.
    pub max: Option<f64>,
    /// Whether the solver may vary this field. `false` pins it.
    pub vary: bool,
    /// 该字段是否为派生量:值由模型的同名方法给出,不参与拟合。
    pub derive: bool,
}

/// A model's parameter layout: which fields are fittable, and how to reach
/// them by index.
///
/// Implemented by `#[derive(Model)]`. The index order is the order the fields
/// are *declared* in, which is also the order [`Self::specs`] returns them in.
/// Every method here must agree on that order; nothing else in the crate
/// assumes anything about it.
pub trait ModelParams {
    /// How this model names itself in a fit report.
    ///
    /// A `&'static str` rather than `std::any::type_name`, whose output format
    /// is explicitly not stable across compilations and carries module paths.
    const MODEL_NAME: &'static str;

    /// How many fittable fields this model has.
    ///
    /// Must equal `specs().len()`. A `const` rather than a method because the
    /// layout is fixed at compile time — the solver reads it in its inner loop
    /// without a call or an allocation. The derive macro emits a literal.
    const NPARAMS: usize;

    /// One spec per fittable field, in field-declaration order.
    ///
    /// Allocates, so it is called when a fit is set up and when a report is
    /// printed — never in the solver's inner loop. Use [`Self::NPARAMS`] there.
    fn specs(&self) -> Vec<ParamSpec>;

    /// Read field `index` as a float.
    ///
    /// # Panics
    ///
    /// Implementations may panic if `index >= NPARAMS`. The solver only ever
    /// passes indices that came from [`Parameters::no_fix_indices`].
    fn get(&self, index: usize) -> f64;

    /// Write field `index`.
    ///
    /// # Panics
    ///
    /// As [`Self::get`].
    fn set(&mut self, index: usize, value: f64);

    /// The parameter struct built from `values`, in index order — the model
    /// at those parameter values.
    ///
    /// Takes `&self` and returns a new value rather than mutating, which is
    /// what lets the solver build perturbed models for its finite-difference
    /// Jacobian without needing `&mut` access to a model it only holds a
    /// shared reference to.
    ///
    /// 派生字段的对应槽位被忽略:它们由 [`Self::refresh_derive`] 从其余字段重算。
    ///
    /// # Panics
    ///
    /// Implementations may panic if `values.len() != NPARAMS`.
    fn at_values(&self, values: &[f64]) -> Self;

    /// 由同名方法重算全部派生字段。
    ///
    /// `#[derive(Model)]` 生成覆写:按字段声明序,逐个调用与字段同名的固有
    /// 方法并把结果写回字段。库在每处构造与写入之后调用本方法,使"派生字段
    /// 恒等于其公式"这一不变量处处成立;普通字段不受影响。缺省体为空,供
    /// 没有派生字段的模型使用。
    ///
    /// 返回:无(就地重算)。
    fn refresh_derive(&mut self) {}

    /// Build the runtime [`Parameters`] collection this model describes.
    ///
    /// # Errors
    ///
    /// Returns [`crate::Error::DuplicateParameter`] if two fields resolve to
    /// the same name — impossible for a derived model, where field names are
    /// unique, but a hand-written impl could still emit one.
    fn parameters(&self) -> Result<Parameters> {
        let mut params = Parameters::new();
        for spec in self.specs() {
            params.push(Parameter {
                name: spec.name,
                value: spec.value,
                stderr: None,
                min: spec.min,
                max: spec.max,
                vary: spec.vary,
                derive: spec.derive,
                init: spec.value,
            })?;
        }
        Ok(params)
    }
}

/// 各参数一阶偏导的读取接口:求解器按与 [`ModelParams::get`] 相同的序读取。
///
/// 由模型的 [`Curve::partials_at`] / [`ComplexCurve::partials_at`] 返回;
/// `#[derive(Model)]` 生成的 `{模型}Partials<T>` 自动实现本 trait。
pub trait PartialValues {
    /// 偏导的标量类型:`f64`(实值模型)或 [`Complex64`](crate::Complex64)(复数模型)。
    type Scalar;

    /// 偏导个数,恒等于模型的 [`ModelParams::NPARAMS`]。
    ///
    /// 返回:参数个数。
    fn len(&self) -> usize;

    /// 读取第 `index` 个参数的一阶偏导。
    ///
    /// 派生字段没有偏导,而 [`Self::len`] 仍把它们计入索引空间,故对派生字段的
    /// 下标调用会 panic;求解器只传变参数的下标,不会触及派生字段。
    ///
    /// * `index` —— 参数下标,序与 [`ModelParams::get`] 一致(字段声明序)。
    ///
    /// 返回:该参数在此点的偏导值。
    fn get(&self, index: usize) -> Self::Scalar;
}

/// 缺省 [`Curve::partials_at`] 的返回载体:不含任何偏导,其值永不会被读取。
///
/// 用户不需要命名本类型;它只是把"该模型不提供解析偏导"落在类型层面的具体化。
pub struct NoPartials<S>(core::marker::PhantomData<S>);

impl<S> PartialValues for NoPartials<S> {
    type Scalar = S;

    /// 返回:恒为 0(缺省体不含偏导)。
    fn len(&self) -> usize {
        0
    }

    /// 返回:永不返回——缺省的 `partials_at` 返回 `None`,本方法不可达。
    fn get(&self, index: usize) -> S {
        unreachable!("NoPartials 不含偏导,index = {index}")
    }
}

/// A curve model: a function of `x` with fittable parameters.
///
/// Implement this for your own structs; `#[derive(Model)]` supplies the
/// [`ModelParams`] half.
///
/// ```
/// use lmfit::{Curve, Model};
///
/// #[derive(Model)]
/// struct Line {
///     #[param(value = 1.0)]
///     slope: f64,
///     #[param(value = 0.0)]
///     intercept: f64,
/// }
///
/// impl Curve for Line {
///     fn eval(&self, x: f64) -> f64 {
///         self.slope * x + self.intercept
///     }
/// }
/// ```
pub trait Curve: ModelParams + Sized {
    /// Evaluate the model at a single point, using this value's parameters.
    ///
    /// Scalar rather than slice-taking: it reads like the formula it encodes,
    /// and it monomorphises, so the residual loop pays no dynamic-dispatch
    /// cost — it inlines straight into the caller.
    fn eval(&self, x: f64) -> f64;

    /// 在 `x` 处按字段声明序给出各参数的一阶偏导 ∂f/∂θ(外部空间值,与
    /// [`eval`](Self::eval) 同一套符号;库负责内部空间换算与取负)。
    ///
    /// 返回 `None` 表示不提供,求解器退回有限差分;偏导含非有限值判雅可比失败。
    /// 覆写时签名原样照抄,返回类型写 `impl PartialValues` 即可,无需命名具体类型;
    /// `#[derive(Model)]` 生成的 `{模型}Partials` 供覆写体内构造。
    ///
    /// * `_x` —— 求导点(缺省体不使用,故以下划线命名)。
    ///
    /// 返回:偏导包;缺省为 `None`。
    fn partials_at(&self, _x: f64) -> Option<impl PartialValues<Scalar = f64>> {
        None::<NoPartials<f64>>
    }

    /// Fit this model to `y` sampled at `x`.
    ///
    /// `self` supplies the starting point: the model's field values are the
    /// initial guesses, and their bounds come from `#[param(...)]`.
    ///
    /// ```
    /// use lmfit::{Curve, Model};
    ///
    /// #[derive(Model)]
    /// struct Line {
    ///     #[param(value = 1.0)]
    ///     slope: f64,
    ///     #[param(value = 0.0)]
    ///     intercept: f64,
    /// }
    /// impl Curve for Line {
    ///     fn eval(&self, x: f64) -> f64 { self.slope * x + self.intercept }
    /// }
    ///
    /// let x = vec![0.0, 1.0, 2.0, 3.0];
    /// let y = vec![1.0, 3.0, 5.0, 7.0];
    ///
    /// let result = Line::default().fit(&y, &x)?;
    /// assert!(result.success);
    /// assert!((result.model.slope - 2.0).abs() < 1e-8);
    /// assert!((result.model.intercept - 1.0).abs() < 1e-8);
    /// # Ok::<(), lmfit::Error>(())
    /// ```
    ///
    /// # Errors
    ///
    /// Fails if `x` and `y` differ in length, if either is empty, or if a
    /// parameter's bounds are degenerate.
    fn fit(&self, y: &[f64], x: &[f64]) -> Result<ModelResult<Self>> {
        crate::solver::fit(self, y, x)
    }

    /// 以逐点测量不确定度 `sigma` 加权拟合。
    ///
    /// `sigma[i]` 是第 `i` 个观测 `y[i]` 的标准不确定度,残差按 `1/sigma[i]`
    /// 加权(即权重 `1/σ²`):σ 小的点对拟合的牵引更强。`chisqr`、`redchi` 与
    /// 协方差都按加权后的量计算;结果里的 `residual` 仍是未加权的原始残差。
    /// 起点、边界与收敛语义与 [`Curve::fit`] 完全一致。
    ///
    /// 一个实务配方:若第 `i` 点是 `n` 次单发测量的平均,则
    /// `sigma[i] = std(shots_i) / sqrt(n)`。
    ///
    /// # Errors
    ///
    /// 与 [`Curve::fit`] 相同,另加两条:`sigma` 长度与数据点数不符,或某项
    /// 不是有限的正数。
    fn fit_sigma(&self, y: &[f64], x: &[f64], sigma: &[f64]) -> Result<ModelResult<Self>> {
        crate::solver::fit_sigma(self, y, x, sigma)
    }
}

/// 复数曲线模型:复数入、复数出,参数为实数。
///
/// 自变量与输出均为复数(实自变量以 `x + 0i` 调用,数值与实数公式逐位一致)。
/// 拟合时每个数据点的复数残差按实部、虚部两个槽位逐点交错进入实数最小二乘
/// (与 numpy `view(float)` 同序,lmfit 口径);[`ModelParams`] 布局、边界变换
/// 与协方差换算全部沿用实数机制。
pub trait ComplexCurve: ModelParams + Sized {
    /// 在单点 `x` 处求复数值。
    fn eval(&self, x: Complex64) -> Complex64;

    /// 同 [`Curve::partials_at`],偏导为复数值(每个参数的偏导是一个复数)。
    ///
    /// * `_x` —— 求导点(缺省体不使用,故以下划线命名)。
    ///
    /// 返回:复数偏导包;缺省为 `None`。
    fn partials_at(&self, _x: Complex64) -> Option<impl PartialValues<Scalar = Complex64>> {
        None::<NoPartials<Complex64>>
    }

    /// 以复数观测 `y` 拟合本模型;自变量 `x` 可实可复。
    ///
    /// `self` 提供起点,语义与 [`Curve::fit`] 一致。
    ///
    /// # Errors
    ///
    /// 与 [`Curve::fit`] 相同:长度不符、数据为空或参数界退化时报错。
    fn fit<X: Copy + Into<Complex64>>(
        &self,
        y: &[Complex64],
        x: &[X],
    ) -> Result<ComplexResult<Self>> {
        crate::solver::fit_complex(self, y, x)
    }

    /// 以逐点测量不确定度 `sigma` 加权拟合复数数据。
    ///
    /// 每个复频点一个 `sigma`,实部与虚部同权(与 numpy 对复数数组取 `std` 的
    /// 口径一致);其余语义与 [`Curve::fit_sigma`] 相同。
    ///
    /// # Errors
    ///
    /// 与 [`ComplexCurve::fit`] 相同,另加 `sigma` 的两个校验错误。
    fn fit_sigma<X: Copy + Into<Complex64>>(
        &self,
        y: &[Complex64],
        x: &[X],
        sigma: &[f64],
    ) -> Result<ComplexResult<Self>> {
        crate::solver::fit_complex_sigma(self, y, x, sigma)
    }
}
