//! The seam between a model, the derive macro, and the solver.
//!
//! Two traits live here, and they split the work cleanly:
//!
//! * [`ModelParams`] is *layout* — which fields exist, in what order, and how
//!   to read and write them. It is generated by `#[derive(Model)]`; users
//!   never write it by hand.
//! * [`Curve`] is *arithmetic* — what the model computes. Users write exactly
//!   one method, and it reads like the formula it implements.
//!
//! Neither the derive macro nor the solver knows about the other. The derive
//! only ever produces an impl of `ModelParams`; the solver only ever consumes
//! one. That is what lets the two evolve independently — a change to how
//! parameters are stored never touches the solver, and a change of solver
//! never touches the macro.

use crate::error::Result;
use crate::parameter::{Parameter, Parameters};
use crate::result::ModelResult;

/// Metadata describing one fittable field of a model.
///
/// Generated per field by `#[derive(Model)]`.
#[derive(Debug, Clone, PartialEq)]
pub struct ParamSpec {
    /// The field's name.
    pub name: String,
    /// Value the fit starts from.
    pub value: f64,
    /// Lower bound, if any.
    pub min: Option<f64>,
    /// Upper bound, if any.
    pub max: Option<f64>,
    /// Whether the solver may vary this field. `false` pins it.
    pub vary: bool,
}

/// A model's parameter layout: which fields are fittable, and how to reach
/// them by index.
///
/// Implemented by `#[derive(Model)]`. The index order is the order the fields
/// are *declared* in, which is also the order [`Self::specs`] returns them in.
/// Every method here must agree on that order; nothing else in the crate
/// assumes anything about it.
pub trait ModelParams {
    /// How this model names itself in a fit report.
    ///
    /// A `&'static str` rather than `std::any::type_name`, whose output format
    /// is explicitly not stable across compilations and carries module paths.
    const MODEL_NAME: &'static str;

    /// How many fittable fields this model has.
    ///
    /// Must equal `specs().len()`. A `const` rather than a method because the
    /// layout is fixed at compile time — the solver reads it in its inner loop
    /// without a call or an allocation. The derive macro emits a literal.
    const NPARAMS: usize;

    /// One spec per fittable field, in field-declaration order.
    ///
    /// Allocates, so it is called when a fit is set up and when a report is
    /// printed — never in the solver's inner loop. Use [`Self::NPARAMS`] there.
    fn specs(&self) -> Vec<ParamSpec>;

    /// Read field `index` as a float.
    ///
    /// # Panics
    ///
    /// Implementations may panic if `index >= NPARAMS`. The solver only ever
    /// passes indices that came from [`Parameters::no_fix_indices`].
    fn get(&self, index: usize) -> f64;

    /// Write field `index`.
    ///
    /// # Panics
    ///
    /// As [`Self::get`].
    fn set(&mut self, index: usize, value: f64);

    /// The parameter struct built from `values`, in index order — the model
    /// at those parameter values.
    ///
    /// Takes `&self` and returns a new value rather than mutating, which is
    /// what lets the solver build perturbed models for its finite-difference
    /// Jacobian without needing `&mut` access to a model it only holds a
    /// shared reference to.
    ///
    /// # Panics
    ///
    /// Implementations may panic if `values.len() != NPARAMS`.
    fn at_values(&self, values: &[f64]) -> Self;

    /// Build the runtime [`Parameters`] collection this model describes.
    ///
    /// # Errors
    ///
    /// Returns [`crate::Error::DuplicateParameter`] if two fields resolve to
    /// the same name — impossible for a derived model, where field names are
    /// unique, but a hand-written impl could still emit one.
    fn parameters(&self) -> Result<Parameters> {
        let mut params = Parameters::new();
        for spec in self.specs() {
            params.push(Parameter {
                name: spec.name,
                value: spec.value,
                min: spec.min,
                max: spec.max,
                vary: spec.vary,
                init: spec.value,
            })?;
        }
        Ok(params)
    }
}

/// A curve model: a function of `x` with fittable parameters.
///
/// Implement this for your own structs; `#[derive(Model)]` supplies the
/// [`ModelParams`] half.
///
/// ```
/// use lmfit::{Curve, Model};
///
/// #[derive(Model)]
/// struct Line {
///     #[param(value = 1.0)]
///     slope: f64,
///     #[param(value = 0.0)]
///     intercept: f64,
/// }
///
/// impl Curve for Line {
///     fn eval(&self, x: f64) -> f64 {
///         self.slope * x + self.intercept
///     }
/// }
/// ```
pub trait Curve: ModelParams + Sized {
    /// Evaluate the model at a single point, using this value's parameters.
    ///
    /// Scalar rather than slice-taking: it reads like the formula it encodes,
    /// and it monomorphises, so the residual loop pays no dynamic-dispatch
    /// cost — it inlines straight into the caller.
    fn eval(&self, x: f64) -> f64;

    /// Fit this model to `y` sampled at `x`.
    ///
    /// `self` supplies the starting point: the model's field values are the
    /// initial guesses, and their bounds come from `#[param(...)]`.
    ///
    /// ```
    /// use lmfit::{Curve, Model};
    ///
    /// #[derive(Model)]
    /// struct Line {
    ///     #[param(value = 1.0)]
    ///     slope: f64,
    ///     #[param(value = 0.0)]
    ///     intercept: f64,
    /// }
    /// impl Curve for Line {
    ///     fn eval(&self, x: f64) -> f64 { self.slope * x + self.intercept }
    /// }
    ///
    /// let x = vec![0.0, 1.0, 2.0, 3.0];
    /// let y = vec![1.0, 3.0, 5.0, 7.0];
    ///
    /// let result = Line::default().fit(&y, &x)?;
    /// assert!(result.success);
    /// assert!((result.model.slope - 2.0).abs() < 1e-8);
    /// assert!((result.model.intercept - 1.0).abs() < 1e-8);
    /// # Ok::<(), lmfit::Error>(())
    /// ```
    ///
    /// # Errors
    ///
    /// Fails if `x` and `y` differ in length, if either is empty, or if a
    /// parameter's bounds are degenerate.
    fn fit(&self, y: &[f64], x: &[f64]) -> Result<ModelResult<Self>> {
        crate::solver::fit(self, y, x)
    }
}
